version: "2"

volumes:
  gems:           # The volume where all gems will be stored
    driver: local

services:
  web:
    image: vovimayhem/ruby:1.9.3-p551
    command: rackup -o 0.0.0.0 config.ru
    entrypoint: /app/development-entrypoint
    ports: [ "9292:9292" ]
    stdin_open: true
    tty: true
    volumes:
      # Mount our app code directory (".") into our app containers at the
      # "/app" folder:
      - .:/app
      # Mount the 'gems' volume into '/app/heroku/ruby/bundle/ruby/2.2.0', which
      # is the path where the heroku/cedar:14 image expects to find installed gems:
      - gems:/usr/local/bundle
    working_dir: /app
